// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAxFtzBf4HRSxtrI-VWDefsINgC4U57_g',
    appId: '1:213733382234:web:f752192a6ac169276e2063',
    messagingSenderId: '213733382234',
    projectId: 'computacion-movil2',
    authDomain: 'computacion-movil2.firebaseapp.com',
    storageBucket: 'computacion-movil2.appspot.com',
    measurementId: 'G-8FWL651KV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGDJa5ZdhdQkbo7RC3WpbkkMAfB-kPfbI',
    appId: '1:213733382234:android:4ff9a3f7245a9eb26e2063',
    messagingSenderId: '213733382234',
    projectId: 'computacion-movil2',
    storageBucket: 'computacion-movil2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIGDfydYjmK0n3Ut84sUKqh3LGMatsqwY',
    appId: '1:213733382234:ios:7ef343a0f930bbb76e2063',
    messagingSenderId: '213733382234',
    projectId: 'computacion-movil2',
    storageBucket: 'computacion-movil2.appspot.com',
    iosBundleId: 'com.example.crudFirebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIGDfydYjmK0n3Ut84sUKqh3LGMatsqwY',
    appId: '1:213733382234:ios:7fa4ed1dc7d6d5336e2063',
    messagingSenderId: '213733382234',
    projectId: 'computacion-movil2',
    storageBucket: 'computacion-movil2.appspot.com',
    iosBundleId: 'com.example.crudFirebase2.RunnerTests',
  );
}
